### ISSUE TITLE
cross-back-end process graph processing

### ISSUE THREAD

**Issue by JeroenVerstraelen** [Open-EO/openeo-aggregator#150]
Follow up on https://github.com/Open-EO/openeo-aggregator/issues/95 and https://github.com/Open-EO/openeo-aggregator/issues/53. Develop a cross-back end process graph splitting implementation that is useful in the current aggregator setup. It should be based on the algorithm developed during the feasibility study.

**Comment by soxofaan** [comment]
> It should be based on the algorithm developed during the feasibility study.

@JeroenVerstraelen  can you point me to the details on this feasibility study?

**Comment by soxofaan** [comment]
There are still some todo's and plenty of idea's for future work, but I decided to merge the current PoC with 9b655205d5e2f85545c229dde86624e7d4e5be33

**Comment by soxofaan** [comment]
Follow up todo's and tasks (WIP)
- #154

**Comment by soxofaan** [comment]
made an initial demo notebook at https://git.vito.be/users/lippenss/repos/workspace/browse/2024/agg150-deep-graph-splitting/agg150-deep-graph-splitting-CDSE.ipynb 
unfortunately the job metadata visualization (including process graph viz) does not work in that viewer (not sure if it is because of bitbucket, or becuase that rich content is not actually stored in the ipynb file)
